# Generated by Django 5.1.4 on 2024-12-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_brand_alter_category_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the product was added to the wishlist.', verbose_name='Date Added')),
                ('product', models.ForeignKey(help_text='The product added to the wishlist.', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(help_text='The user who added the product to the wishlist.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'indexes': [models.Index(fields=['user'], name='wishlist_wi_user_id_ec8321_idx'), models.Index(fields=['product'], name='wishlist_wi_product_1bb998_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
