CREATE TABLE "Brand" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE,
  "slug" varchar(255) UNIQUE,
  "description" text,
  "logo" varchar,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "Category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE,
  "slug" varchar(150) UNIQUE,
  "is_active" boolean,
  "parent_id" int,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "ProductType" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE,
  "slug" varchar(255) UNIQUE
);

CREATE TABLE "ProductAttribute" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE,
  "description" text,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "ProductAttributeValue" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_attribute_id" int,
  "attribute_value" varchar(255),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "Product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "web_id" varchar(50) UNIQUE,
  "slug" varchar(255),
  "name" varchar(255),
  "description" text,
  "brand_id" int,
  "category_id" int,
  "is_active" boolean,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "Media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "image" varchar,
  "is_feature" boolean,
  "ordering" int,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "ProductInventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sku" varchar(20) UNIQUE,
  "upc" varchar(12) UNIQUE,
  "product_type_id" int,
  "product_id" int,
  "stock" int,
  "is_active" boolean,
  "retail_price" decimal,
  "store_price" decimal,
  "sale_price" decimal,
  "weight" decimal,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "ProductReview" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "product_id" int,
  "title" varchar(255),
  "review" text,
  "rating" int,
  "date" datetime,
  "show_name" boolean,
  "is_approved" boolean
);

CREATE TABLE "Wishlist" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "product_id" int,
  "added_at" datetime
);

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(150) UNIQUE,
  "email" varchar(254) UNIQUE,
  "first_name" varchar(150),
  "last_name" varchar(150),
  "password" varchar(128),
  "is_active" boolean,
  "is_staff" boolean,
  "is_superuser" boolean,
  "date_joined" datetime,
  "last_login" datetime
);

ALTER TABLE "ProductAttributeValue" ADD FOREIGN KEY ("product_attribute_id") REFERENCES "ProductAttribute" ("id");

ALTER TABLE "Product" ADD FOREIGN KEY ("brand_id") REFERENCES "Brand" ("id");

ALTER TABLE "Product" ADD FOREIGN KEY ("category_id") REFERENCES "Category" ("id");

ALTER TABLE "Media" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("id");

ALTER TABLE "ProductInventory" ADD FOREIGN KEY ("product_type_id") REFERENCES "ProductType" ("id");

ALTER TABLE "ProductInventory" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("id");

ALTER TABLE "ProductReview" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "ProductReview" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("id");

ALTER TABLE "Wishlist" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Wishlist" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("id");

ALTER TABLE "Category" ADD FOREIGN KEY ("parent_id") REFERENCES "Category" ("id");

ALTER TABLE "ProductInventory" ADD FOREIGN KEY ("retail_price") REFERENCES "ProductInventory" ("stock");
