# Generated by Django 5.1.4 on 2024-12-07 07:44

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required, max 100 characters', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='Required, letters, numbers, underscore, or hyphens', max_length=150, unique=True, verbose_name='Category Safe URL')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this category is active.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Format: Y-m-d H:M:S', verbose_name='Date Category Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Format: Y-m-d H:M:S', verbose_name='Date Category Updated')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category', verbose_name='Parent of Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='categories__name_e3ad98_idx'), models.Index(fields=['slug'], name='categories__slug_9b1a28_idx')],
                'unique_together': {('slug', 'parent')},
            },
        ),
    ]
