# Generated by Django 5.1.4 on 2024-12-07 07:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_brand_alter_category_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional, max 255 characters', max_length=255, null=True, verbose_name='Review Title')),
                ('review', models.TextField(help_text='Required. The content of the review.', verbose_name='Review Content')),
                ('rating', models.IntegerField(help_text='Required. An integer between 1 and 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the review was created.', verbose_name='Date Created')),
                ('show_name', models.BooleanField(default=True, help_text="If checked, the user's name will be displayed.", verbose_name='Show Name')),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether the review is approved by an admin.', verbose_name='Is Approved')),
                ('product', models.ForeignKey(help_text='The product that this review is for.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(help_text='The user who wrote the review.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['product'], name='reviews_pro_product_49cbbb_idx'), models.Index(fields=['user'], name='reviews_pro_user_id_3d1523_idx'), models.Index(fields=['is_approved'], name='reviews_pro_is_appr_df6bfc_idx')],
            },
        ),
    ]
