# Generated by Django 5.1.4 on 2024-12-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_comment_reviewvote_delete_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
