# Generated by Django 5.1.4 on 2024-12-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expiration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
