openapi: 3.0.3
info:
  title: Ecommerce-Django-REST-APIs
  version: 1.0.0
  description: This is the API documentation for 'Ecommerce-Django-REST-APIs'.
paths:
  /admin/categories/:
    get:
      operationId: admin_categories_list
      description: |-
        Allows admin to list and create categories.
        Requires admin privileges.
      parameters:
      - in: query
        name: is_active
        schema:
          type: boolean
      - in: query
        name: name
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - in: query
        name: parent
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - Admin - Category
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCategoryList'
          description: ''
    post:
      operationId: admin_categories_create
      description: |-
        Allows admin to list and create categories.
        Requires admin privileges.
      tags:
      - Admin - Category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Category'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Category'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
  /admin/categories/{id}/:
    get:
      operationId: admin_categories_retrieve
      description: |-
        Allows admin to retrieve, update or delete a specific category by pk.
        Requires admin privileges.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Admin - Category
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
    put:
      operationId: admin_categories_update
      description: |-
        Allows admin to retrieve, update or delete a specific category by pk.
        Requires admin privileges.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Admin - Category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Category'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Category'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
    patch:
      operationId: admin_categories_partial_update
      description: |-
        Allows admin to retrieve, update or delete a specific category by pk.
        Requires admin privileges.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Admin - Category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCategory'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCategory'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCategory'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
    delete:
      operationId: admin_categories_destroy
      description: |-
        Allows admin to retrieve, update or delete a specific category by pk.
        Requires admin privileges.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Admin - Category
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /categories/:
    get:
      operationId: categories_list
      description: |-
        Returns a list of all active categories.
        Only active categories are visible to the end user.
      parameters:
      - in: query
        name: name
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - in: query
        name: parent
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - Category - List
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCategoryList'
          description: ''
  /categories/{id}/:
    get:
      operationId: categories_retrieve
      description: Returns the details of a single active category by its primary
        key (pk).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Category - Detail
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Category Name
          description: Required, max 100 characters
          maxLength: 100
        slug:
          type: string
          title: Category Safe URL
          description: Required, letters, numbers, underscore, or hyphens
          maxLength: 150
          pattern: ^[-a-zA-Z0-9_]+$
        is_active:
          type: boolean
          description: Designates whether this category is active.
        parent:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          title: Date Category Created
          description: 'Format: Y-m-d H:M:S'
        updated_at:
          type: string
          format: date-time
          readOnly: true
          title: Date Category Updated
          description: 'Format: Y-m-d H:M:S'
      required:
      - created_at
      - id
      - name
      - slug
      - updated_at
    PaginatedCategoryList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Category'
    PatchedCategory:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          title: Category Name
          description: Required, max 100 characters
          maxLength: 100
        slug:
          type: string
          title: Category Safe URL
          description: Required, letters, numbers, underscore, or hyphens
          maxLength: 150
          pattern: ^[-a-zA-Z0-9_]+$
        is_active:
          type: boolean
          description: Designates whether this category is active.
        parent:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
          title: Date Category Created
          description: 'Format: Y-m-d H:M:S'
        updated_at:
          type: string
          format: date-time
          readOnly: true
          title: Date Category Updated
          description: 'Format: Y-m-d H:M:S'
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
- name: Category - List
  description: Endpoints for listing all active categories accessible to users.
- name: Category - Detail
  description: Endpoint for retrieving the details of a single active category by
    pk.
- name: Admin - Category
  description: Admin endpoints for managing categories, including listing, creating,
    updating, and deleting categories.
