# Generated by Django 5.1.4 on 2024-12-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'ordering': ['id'], 'verbose_name': 'Product Attribute Value', 'verbose_name_plural': 'Product Attribute Values'},
        ),
    ]
